; ---------------------------------------------------------
; GLOBAL SETTINGS (Inherited by all environments below)
; ---------------------------------------------------------
[env]
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0

; ---------------------------------------------------------
; HARDWARE ENVIRONMENT (NodeMCU)
; ---------------------------------------------------------
[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
test_framework = unity
test_filter = test_embedded_* ; Only runs tests meant for hardware
build_src_filter = +<*> -<.git/*> -<examples/*> -<tests/*>

; ---------------------------------------------------------
; NATIVE ENVIRONMENT (PC Testing)
; ---------------------------------------------------------
[env:native]
platform = native
test_framework = googletest
test_filter = test_logic_* ; Only runs pure C++ logic tests