; Environment for testing on the actual hardware
[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
test_framework = unity
test_filter = test_embedded_* ; Only runs tests meant for hardware

; Environment for testing logic instantly on your PC
[env:native]
platform = native
test_framework = googletest
test_filter = test_logic_* ; Only runs pure C++ logic tests