; ---------------------------------------------------------
; GLOBAL SETTINGS (Inherited by all environments below)
; ---------------------------------------------------------
[env]
lib_deps =
    ottowinter/ESPAsyncWebServer-esphome @ ^3.1.0
    esphome/AsyncTCP-esphome @ ^2.1.1
    bblanchon/ArduinoJson @ ^7.0.0
build_src_filter = +<src> +<include> -<.git> -<examples>

; ---------------------------------------------------------
; HARDWARE ENVIRONMENT (NodeMCU)
; ---------------------------------------------------------
[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
build_src_filter = +<src> +<include> -<.git> -<examples>
; Uncomment the line below to disable HTML minification (requires: pip install css-html-js-minify)
; minify_assets = false
